### ISSUE TITLE
failed import polybin

### ISSUE THREAD

**Issue by satinex** [therealOri/PolyLock#6]
![image](https://github.com/user-attachments/assets/042a0f9c-6105-447f-b510-d30e407b5837)

**Comment by therealOri** [comment]
Hmm, I can't seem to be able to replicate this issue. Could you tell me a bit more about your setup/system?

What version of python are you using?
Are you using anaconda/conda?
Anything else really that'd potentially be able to help. 



As for my research into the error, it seems like everything is revolving around `pywin32`.
https://stackoverflow.com/questions/58612306/how-to-fix-importerror-dll-load-failed-while-importing-win32api


As of right now, I am unsure if this issue is something on my end with PolyLock that needs to be fixed or an issue on your end. Please feel free to try out some of the solutions in the stackoverflow post and then get back to me with the results to see if anything worked.

**Comment by satinex** [comment]
> Hmm, I can't seem to be able to replicate this issue. Could you tell me a bit more about your setup/system?
> 
> What version of python are you using? Are you using anaconda/conda? Anything else really that'd potentially be able to help.
> 
> As for my research into the error, it seems like everything is revolving around `pywin32`. https://stackoverflow.com/questions/58612306/how-to-fix-importerror-dll-load-failed-while-importing-win32api
> 
> As of right now, I am unsure if this issue is something on my end with PolyLock that needs to be fixed or an issue on your end. Please feel free to try out some of the solutions in the stackoverflow post and then get back to me with the results to see if anything worked.

Windows 11, Python3.11.5
yes im using anaconda too 3.11.5

**Comment by therealOri** [comment]
Perhaps this should help?: https://stackoverflow.com/questions/58026742/anaconda-issue-dll-load-failed

Voted answer:
"A very common reason for this error is that the **conda environment hasn't been properly activated**. This can be done by either using the `"Anaconda prompt"` or by e.g. starting the cmd shell and then running C:\users\user_name>`conda activate`. This will change the prompt to `(base) C:\users\user_name>` and add serveral Anaconda subfolders to the `PATH`. Then Python should be started from there via (base) C:\users\user_name> `python`.


Feel free to give this a try and see if it works?

**Comment by therealOri** [comment]
This issue has been inactive/stale now for about 3 days, I will assume that your issue has been resolved with the provided solutions and I will be closing this issue.

If your issue still persists and are having trouble then please don't hesitate to re open this issue or comment here again.
